#!/usr/bin/env bash
set -e

trap cleanup SIGINT EXIT
#trap handle_resize SIGWINCH

ROWS=$(tput lines)
COLS=$(tput cols)
CONTENT_ROWS=$((ROWS - 1))
OLD_STTY=$(stty -g)
LEAVE=1
SERVER='https://ntfy.daedalist.net/'

cleanup() {
    #wait
    if [[ $LEAVE < 1 ]]; then
        # leave message
        send_msg "$key" "${username}: has left"
    fi
    LEAVE=$((LEAVE - 1))

    printf "\033[r"      # reset scroll region
    tput rmcup           # restore original screen
    stty "$OLD_STTY"

    #echo "cleanup" $nfty_listen_PID
    if kill -0 $CURL_PID 2>/dev/null; then
        #echo "cleanup" "$CURL_PID"
        kill ${CURL_PID}
    fi
    exit
}

preflight() {
    #local requires=( curl )
    if ! [[ "$BASH_VERSION" =~ ^5.+ ]]; then
        echo "Needs a newer version of Bash"
        exit 1
    fi
}

random_name() {
    local vowels=( a e i o u y );
    local consonants=( b c d f g h j k l m n p q r s t v w x y z);
    local result=

    while ((${#result} < 4)); do

        #local limit=5
        #for ((i = 0; i < limit; ++i)); do
            if [[ $(($RANDOM % 2)) == 0 ]]; then
                local rndc=$(($RANDOM % ${#consonants[@]}))
                local rndv=$(($RANDOM % ${#vowels[@]}))
                local tmp="${consonants[rndc]}${vowels[rndv]}"
                result="$result$tmp"
            fi
            if [[ $(($RANDOM % 2)) == 0 ]]; then
                local rndc=$(($RANDOM % ${#consonants[@]}))
                local rndcc=$(($RANDOM % ${#consonants[@]}))
                local rndv=$(($RANDOM % ${#vowels[@]}))
                local tmp="${consonants[rndc]}${vowels[rndv]}${consonants[rndcc]}"
                result="$result$tmp"
            fi
            if [[ $(($RANDOM % 2)) == 0 ]]; then
                local rndc=$(($RANDOM % ${#consonants[@]}))
                local rndcc=$(($RANDOM % ${#consonants[@]}))
                local rndv=$(($RANDOM % ${#vowels[@]}))
                local tmp="${vowels[rndv]}${consonants[rndcc]}"
                result="$result$tmp"
            fi
        #done
    done

    echo "$result"
}

encrypt_msg() {
    local key="$1"; shift
    local msg="$1"
    #echo "$msg" | openssl enc -aes-256-cbc -pbkdf2 -base64 -nosalt -k "$key"
    echo "$msg" | gpg --passphrase "$key" --batch --yes --symmetric -a
}

decrypt_msg() {
    local key="$1"; shift
    local msg="$@"
        #echo "$msg" #| openssl enc -d -aes-256-cbc -pbkdf2 -base64 -nosalt -k "$key"
        gpg --decrypt --passphrase "$key" --batch --yes --quiet <<< "$msg"
}

MESSAGE_BUFFER_OFFSET=0
SCROLLBACK_OFFSET=0
MESSAGE_BUFFER=()
draw_messages() {
    local read_fd="$1"; shift
    local msg

    #MESSAGE_BUFFER_OFFSET=$((${#MESSAGE_BUFFER[@]} - $CONTENT_ROWS))
    #MESSAGE_BUFFER_OFFSET=${#MESSAGE_BUFFER[@]}
    while IFS= read -r -u $read_fd msg; do
        local MESSAGE_BUFFER_LEN=${#MESSAGE_BUFFER[@]}
        MESSAGE_BUFFER_OFFSET=$(max 0 $(( $MESSAGE_BUFFER_LEN - $CONTENT_ROWS + 1)))
        #tput cup $((LINES - 2)) 0
        if [[ -n "$msg" ]]; then
            MESSAGE_BUFFER+=( "$msg" )
            tput sc
            tput civis
            for ((i = 0; i < CONTENT_ROWS; ++i)); do
                tput cup $(($i))  0
                printf "\033[2K"  # clear the line
                echo -n "${MESSAGE_BUFFER[MESSAGE_BUFFER_OFFSET + i]}"
                #echo -n "${MESSAGE_BUFFER_LEN}"
            done
            tput rc
            #tput cr
            tput cup $((LINES - 1)) 2
            tput cnorm
        fi
    done
}

send_msg() {
    local key="$1"; shift
    echo "$@" | curl -s -d @- "${SERVER}/${key}" >/dev/null
}

#print_message() {
#    # Save cursor, move to top region, print (it will scroll naturally), restore
#    tput sc
#    tput cup ${CONTENT_ROWS}  0
#    echo "$@"
#    tput rc
#}

handle_resize() {
    ROWS=$(tput lines)
    COLS=$(tput cols)
    CONTENT_ROWS=$((ROWS - 1))
    tput smcup
    tput clear
    printf "\033[1;${CONTENT_ROWS}r"  # reset scroll region
    #draw_input "$usr_input"
}

max() {
    local x=$1; shift
    local y=$1
    if [[ $x -lt $y ]]; then
        echo $y
    else
        echo $x
    fi
}

draw_input() {
    IFS=
    local text="$1"
    local pos="${2:-${#text}}"
    local cols=$(($COLS - 3))
    tput cup $((ROWS - 1)) 0
    printf "\033[2K"  # clear the line
    #if [[ $pos -ge $cols ]]; then
        local min=$(max 0 $(($pos - $cols)))
        printf "> %s" "${text:$min:$cols}"
        tput cup $((ROWS - 1)) $((pos + 2))
    #else
    #    printf "> %s" "$text"
    #    tput cup $((ROWS - 1)) $((pos + 2))
    #fi
}

main() {
    username="${1}"
    key="${2:-0xDEADBEA7}"
    if [[ -z $username ]]; then
        username="$(random_name)"
    fi

    preflight

    tput smcup
    tput clear
    #printf "\033[1;${CONTENT_ROWS}r"

    echo "To exit use CTRL+c"

    coproc ntfy_listen ( curl -s --no-buffer -N "${SERVER}/${key}/raw?since=720m" )
    #coproc ntfy_listen ( cat )
    CURL_PID=$ntfy_listen_PID
    exec {READ_FD}<&${ntfy_listen[0]}
    draw_messages $READ_FD &

    ## arrival message
    send_msg "$key" "${username}: has arrived"

    local usr_input=( )
    local cur_pos=0
    local char
    local esc
    draw_input
    while IFS= read -r -s -n1 char; do
        if [[ -z "$char" ]]; then
            if [[ -n "${#usr_input[@]}" ]]; then
                send_msg "$key" "${username}: ${usr_input[*]}"
                #echo "$key" "${username}: ${usr_input[*]}" >&${ntfy_listen[1]}
                cur_pos=0
                usr_input=()
            fi
        elif [[ $char == $'\177' ]]; then  # backspace
            local usr_input_len=${#usr_input[@]}
            (( cur_pos == 0 )) && continue || true
            (( cur_pos > 0 )) && (( cur_pos-- )) || true
            for ((i = cur_pos; i <= usr_input_len; ++i )); do
                usr_input[i]="${usr_input[i+1]}"
            done
            unset usr_input[usr_input_len - 1]
            usr_input=( ${usr_input[@]} )
        elif [[ $char == $'\033' ]]; then # escape sequences
            #cur_pos=${#usr_input}
            read -r -s -n5 -t 0.05 esc || true  # consume up to 5 more bytes
            case "$esc" in
                '[D')  # left arrow
                    (( cur_pos > 0 )) && (( cur_pos-- )) || true
                    ;;
                '[C')  # right arrow
                    (( cur_pos < ${#usr_input[@]} )) && (( cur_pos++ )) || true
                        ;;
                    *)  # discard other sequences
                        ;;
                esac
            #draw_input "$usr_input"
            #draw_input "$usr_input" "$cur_pos"
            #continue
        else
            #copy forward
            usr_input_len=${#usr_input[@]}
            for ((i = usr_input_len - 1; i >= cur_pos; --i )); do
                usr_input[i+1]="${usr_input[i]}"
            done
            usr_input[cur_pos++]="$char"
        fi
    draw_input "${usr_input[*]}" "$cur_pos"
    done


}; main "$@"
