#!/usr/bin/env bash
#set -e

trap cleanup INT SIGINT EXIT
trap handle_resize SIGWINCH

ROWS=$(tput lines)
COLS=$(tput cols)
SCROLL=0
CONTENT_ROWS=$((ROWS - 1))
OLD_STTY=$(stty -g)
SERVER='https://ntfy.daedalist.net/'

LEAVE=1
cleanup() {
    if [[ $LEAVE < 1 ]]; then
        # leave message
        send_msg "$key" "${username}:" "has left"
    fi
    LEAVE=$((LEAVE - 1))

    tput cnorm
    printf "\033[r"      # reset scroll region
    tput rmcup           # restore original screen
    stty "$OLD_STTY"

    if kill -0 $CURL_PID 2>/dev/null; then
        kill ${CURL_PID}
    fi
    if kill -0 $input_handler_pid 2>/dev/null; then
        kill $input_handler_pid
    fi
    if [[ -p /tmp/EVENT_BUS ]]; then
        rm -f /tmp/EVENT_BUS
    fi
    exit
}

preflight() {
    local requires=( curl )
    if ! [[ "$BASH_VERSION" =~ ^5.+ ]]; then
        echo "Needs a newer version of Bash"
        exit 1
    fi

    for cmd in "${requires[@]}"; do
        if ! command -v "$cmd" >/dev/null; then
            echo "requires $cmd to be installed"
            exit 1
        fi
    done

    if ! [[ -p /tmp/EVENT_BUS ]]; then
        mkfifo /tmp/EVENT_BUS
    fi
}

random_name() {
    local vowels=( a e i o u y );
    local consonants=( b c d f g h j k l m n p q r s t v w x y z);
    local rejects=( yy xy qx xq pq wq )
    local result

    while ((${#result} < 4)); do
        local rndc rndv rndcc tmp
        if [[ $(($RANDOM % 2)) == 0 ]]; then
            rndc=$(($RANDOM % ${#consonants[@]}))
            rndv=$(($RANDOM % ${#vowels[@]}))
            tmp="${consonants[rndc]}${vowels[rndv]}"
        fi
        if [[ $(($RANDOM % 2)) == 0 ]]; then
            rndc=$(($RANDOM % ${#consonants[@]}))
            rndcc=$(($RANDOM % ${#consonants[@]}))
            rndv=$(($RANDOM % ${#vowels[@]}))
            tmp="${consonants[rndc]}${vowels[rndv]}${consonants[rndcc]}"
        fi
        if [[ $(($RANDOM % 2)) == 0 ]]; then
            rndc=$(($RANDOM % ${#consonants[@]}))
            rndcc=$(($RANDOM % ${#consonants[@]}))
            rndv=$(($RANDOM % ${#vowels[@]}))
            tmp="${vowels[rndv]}${consonants[rndcc]}"
        fi
        #if [[ "${rejects[*]}" =~ "$tmp" ]]; then
        #    tmp=''
        #fi
        result="$result$tmp"
    done

    echo "$result"
}

#encrypt_msg() {
#    local key="$1"; shift
#    local msg="$1"
#    #echo "$msg" | openssl enc -aes-256-cbc -pbkdf2 -base64 -nosalt -k "$key"
#    echo "$msg" | gpg --passphrase "$key" --batch --yes --symmetric -a
#}
#
#decrypt_msg() {
#    local key="$1"; shift
#    local msg="$@"
#        #echo "$msg" #| openssl enc -d -aes-256-cbc -pbkdf2 -base64 -nosalt -k "$key"
#        gpg --decrypt --passphrase "$key" --batch --yes --quiet <<< "$msg"
#}

MESSAGE_BUFFER_OFFSET=0
SCROLLBACK_OFFSET=0
MESSAGE_BUFFER=()
draw_messages() {
    local read_fd="$1"; shift
    local msg

    while IFS= read -r -u $read_fd msg; do
        if [[ -n "$msg" ]]; then
            write "MSG: $msg"
        fi
    done
}

write() {
    echo "$@" >/dev/ttys002
}

pad() {
    local string=$1; shift
    local last=$1; shift
    local first=$((${#string} - 1))
    local tmp
    while ((++first < last)); do
        tmp+=" "
    done
    printf '%s' "${string}${tmp}"
}

clamp() {
    local min=$1; shift
    local max=$1; shift
    local x=$1
    if [[ $x -lt $min ]]; then
        echo $min
    elif [[ $x -gt $max ]]; then
        echo $max
    else
        echo $x
    fi
}

SCROLL=0
render_messages() {
    tput sc
    #tput civis
    local screen_buffer=()
    SCROLL=$(min 0 $SCROLL)
    SCROLL=$(max $((-screen_buffer_offset)) $SCROLL)
    for ((i = 0; i < ${#MESSAGE_BUFFER[@]}; ++i)); do
        local first=0
        local last=${#MESSAGE_BUFFER[i]}
        while ((first < last)); do
            screen_buffer+=( "${MESSAGE_BUFFER[i]:$first:$((COLS - 1))}" )
            first=$((first + COLS - 1))
        done
    done

    local screen_buffer_len=${#screen_buffer[@]}
    screen_buffer_offset=$(max 0 $(( $screen_buffer_len - $CONTENT_ROWS )))

    # draw scrollbar
    if [[ $SCROLL < 0 && $screen_buffer_len -gt $CONTENT_ROWS ]]; then
        local bar=$(clamp 1 $CONTENT_ROWS $(( CONTENT_ROWS * CONTENT_ROWS / screen_buffer_len )))
        local max_bar_offset=$(( CONTENT_ROWS - bar ))
        local max_scroll=$(( screen_buffer_len - CONTENT_ROWS ))
        local bar_offset=$(( max_bar_offset * (max_scroll + SCROLL) / max_scroll ))

        for ((i = bar_offset + 1; i < bar_offset + bar + 2; ++i)); do
            #tput cup $((i)) $((COLS - 1))
            #printf "\033[7m \033[0m"
            local tmp="${screen_buffer[i - 1 + screen_buffer_offset + SCROLL]}"
            screen_buffer[i - 1 + screen_buffer_offset + SCROLL]="$(pad "${tmp}" $((COLS - 1)) )█"
        done
    fi

    for ((i = 0; i < CONTENT_ROWS; ++i)); do
        tput cup $(($i))  0
        #printf "\r%s\033[2K"  # clear the line
        #echo -n "${screen_buffer[screen_buffer_offset + i + SCROLL]}"
        printf '\r%s\033[K' "${screen_buffer[screen_buffer_offset + i + SCROLL]}"
    done


    tput rc
}

send_msg() {
    local key="$1"; shift
    local username="$1"; shift
    if [[ -z "$@" ]]; then
        return
    fi
    if [[ -n $CONCORD_CAT ]]; then
        echo "$username $@" >&$WRITE_FD
        return
    fi
    echo "$username $@" | curl -s -d @- "${SERVER}/${key}" >/dev/null
}

handle_resize() {
    ROWS=$(tput lines)
    COLS=$(tput cols)
    CONTENT_ROWS=$((ROWS - 1))
    #tput smcup
    #tput clear
    #printf "\033[1;${CONTENT_ROWS}r"  # reset scroll region
    render_messages
    render_messages
    draw_input
    draw_input "$usr_input"
}

max() {
    if [[ $1 -lt $2 ]]; then
        echo $2
    else
        echo $1
    fi
}

min() {
    if [[ $1 -lt $2 ]]; then
        echo $1
    else
        echo $2
    fi
}

draw_input() {
    local text="$1"
    local pos="${2:-${#text}}"
    local cols=$(($COLS - 3))
    #tput civis
    tput cup $((ROWS - 1)) 0
    #printf "\033[2K"  # clear the line
    local min=$(max 0 $(($pos - $cols)))
    printf "\r%s\033[K" "> ${text:$min:$cols}"
    tput cup $((ROWS - 1)) $((pos + 2)) # real cursor is hidden here
    printf "\033[7m${text:$((pos)):1}\033[0m" # invert cursor
    if [[ $pos -ge ${#text} ]]; then
        printf "\033[7m \033[0m" # invert cursor at end of input
    fi
    #tput cnorm
}

input_handler() {
    local write_fd="$1"; shift
    local username="$1"
    local usr_input=()
    local cur_pos=0
    local char
    local esc
    while IFS= read -r -s -n1 char; do
        if [[ -z "$char" ]]; then
            if [[ -n "${#usr_input[@]}" ]]; then
                write "CTRL_KEYS: ENTER $(IFS=''; printf '%s' "${usr_input[*]}")"
                cur_pos=0
                usr_input=()
            fi
        elif [[ $char == $'\177' ]]; then  # backspace
            local usr_input_len="${#usr_input[@]}"
            (( cur_pos == 0 )) && continue || true
            (( cur_pos > 0 )) && (( cur_pos-- )) || true
            for ((i = cur_pos; i <= usr_input_len; ++i )); do
                usr_input[i]="${usr_input[i+1]}"
            done
            local input=()
            for ((i = 0; i < $(( ${#usr_input[@]} - 2)); ++i )); do
                input+=( "${usr_input[i]}" )
            done
            usr_input=( "${input[@]}" )

        elif [[ $char == $'\033' ]]; then # escape sequences
            local one two three four five
            read -r -s -n5 -t 0.01 esc || true  # consume up to 5 more bytes
            #read -r -s -n5 one two three four five || true  # consume up to 5 more bytes
            #esc="$one$two$three$four$five"
            case "$esc" in
                '[A')  # up arrow
                    write "CTRL_KEYS: UP"
                    ;;
                '[B')  # down arrow
                    write "CTRL_KEYS: DOWN"
                    ;;
                '[D')  # left arrow
                    (( cur_pos > 0 )) && (( cur_pos-- )) || true
                    ;;
                '[C')  # right arrow
                    (( cur_pos < ${#usr_input[@]} )) && (( cur_pos++ )) || true
                        ;;
                    *)  # discard other sequences
                        ;;
                esac
        else
            local usr_input_len=${#usr_input[@]}
            for ((i = usr_input_len - 1; i >= cur_pos; --i )); do
                usr_input[i+1]="${usr_input[i]}"
            done
            usr_input[cur_pos++]="$char"
        fi
        write "INPUT_KEYS: "$cur_pos" $(IFS=''; printf '%s' "${usr_input[*]}")"
    done
}

test_events() {
    while : ; do
        echo $(date) > /tmp/EVENT_BUS
        sleep 1
    done
}

write() {
    echo "$@" > /tmp/EVENT_BUS
}

test_log() {
    echo "$@" > /dev/ttys002
}

main() {
    username="${1}"
    key="${2:-0xDEADBEA7}"
    if [[ -z $username ]]; then
        username="$(random_name)"
    fi

    preflight

    tput smcup
    tput clear
    tput civis

    if [[ -n $CONCORD_CAT ]]; then
        coproc ntfy_listen  ( cat ) # for offline testing
    else
        coproc ntfy_listen ( curl -s --no-buffer -N "${SERVER}/${key}/raw?since=720m" )
    fi
    CURL_PID=$ntfy_listen_PID
    exec {READ_FD}<&${ntfy_listen[0]}
    exec {WRITE_FD}<&${ntfy_listen[1]}
    draw_messages $READ_FD &
    input_handler $WRITE_FD "$username" &
    input_handler_pid=$!

    # arrival message
    send_msg "$key" "${username}:" "has arrived"

    render_messages
    draw_input

    local event
    local _discard cur_pos e
    while : ; do
        while read -r event; do
            if [[ "$event" =~ ^INPUT_KEYS: ]]; then
                IFS=' ' read -r _discard cur_pos e <<< "$event"
                usr_input="$e"
                draw_input "${usr_input}" "$cur_pos"
            elif [[ "$event" =~ ^CTRL_KEYS: ]]; then
                IFS=' ' read -r _discard e <<< "$event"
                if [[ "$e" == UP ]]; then
                    ((--SCROLL))
                    render_messages
                elif [[ "$e" == DOWN ]]; then
                    ((++SCROLL))
                    render_messages
                elif [[ "$e" =~ ^ENTER ]]; then
                    IFS=' ' read -r _discard e <<< "$e"
                    send_msg "$key" "${username}:" "${e}"
                    SCROLL=0
                    render_messages
                fi
            elif [[ "$event" =~ ^MSG: ]]; then
                IFS=' ' read -r _discard e <<< "$event"
                # keep from scrolling when not at newest message
                [[ $SCROLL -lt 0 ]] && ((--SCROLL))
                MESSAGE_BUFFER+=( "$e" )
                render_messages
            fi
        done < /tmp/EVENT_BUS
    done

}; main "$@"
